export const AVIATION_IMAGES = {
  dashboard: '/images/dashboard-hero.jpg',
  vuelos: '/images/staff-vuelos.jpg',
  clienteVuelos: '/images/cliente-vuelos.jpg',
  clienteReservas: '/images/cliente-reservas.jpg',
  clientePasajeros: '/images/cliente-pasajeros.jpg',
  aeropuertos: '/images/staff-aeropuertos.jpg',
  aeronaves: '/images/staff-aeronaves.jpg',
  tiposAvion: '/images/staff-tipos-avion.jpg',
  tripulacion: '/images/staff-tripulacion.jpg',
  escalas: '/images/staff-escalas.jpg',
  estadosVuelo: '/images/staff-vuelos.jpg',
  asignaciones: '/images/staff-asignaciones.jpg',
  aerolineas: '/images/staff-aerolineas.jpg',
  paises: '/images/staff-paises.jpg',
  ciudades: '/images/staff-ciudades.jpg',
  terminales: '/images/staff-terminales.jpg',
  puertas: '/images/staff-puertas.jpg',
  controlTower: '/images/staff-control.jpg',
  reservas: '/images/cliente-reservas.jpg',
  pasajeros: '/images/cliente-pasajeros.jpg',
  checkins: '/images/staff-checkins.jpg',
  asientos: '/images/staff-asientos.jpg',
  tarifas: '/images/staff-tarifas.jpg',
  facturas: '/images/staff-facturas.jpg',
  pagos: '/images/staff-pagos.jpg',
  metodosPago: '/images/staff-metodos-pago.jpg',
  servicios: '/images/staff-servicios.jpg',
  reservaServicios: '/images/staff-reserva-servicios.jpg',
  equipajes: '/images/staff-equipajes.jpg',
  notificaciones: '/images/staff-notificaciones.jpg',
} as const;

export function fallbackDeImagen(src: string): string | undefined {
  for (const key of Object.keys(AVIATION_IMAGES) as Array<keyof typeof AVIATION_IMAGES>) {
    if (AVIATION_IMAGES[key] === src) return AVIATION_IMAGES_FALLBACK[key];
  }
  return undefined;
}

export const AVIATION_IMAGES_FALLBACK: Record<keyof typeof AVIATION_IMAGES, string> = {
  dashboard: '/images/dashboard-hero.svg',
  vuelos: '/images/staff-vuelos.svg',
  clienteVuelos: '/images/cliente-vuelos.svg',
  clienteReservas: '/images/cliente-reservas.svg',
  clientePasajeros: '/images/cliente-pasajeros.svg',
  aeropuertos: '/images/staff-aeropuertos.svg',
  aeronaves: '/images/staff-aeronaves.svg',
  tiposAvion: '/images/staff-tipos-avion.svg',
  tripulacion: '/images/staff-tripulacion.svg',
  escalas: '/images/staff-escalas.svg',
  estadosVuelo: '/images/staff-vuelos.svg',
  asignaciones: '/images/staff-asignaciones.svg',
  aerolineas: '/images/staff-aerolineas.svg',
  paises: '/images/staff-paises.svg',
  ciudades: '/images/staff-ciudades.svg',
  terminales: '/images/staff-terminales.svg',
  puertas: '/images/staff-puertas.svg',
  controlTower: '/images/staff-control.svg',
  reservas: '/images/cliente-reservas.svg',
  pasajeros: '/images/cliente-pasajeros.svg',
  checkins: '/images/staff-terminales.svg',
  asientos: '/images/staff-vuelos.svg',
  tarifas: '/images/staff-aerolineas.svg',
  facturas: '/images/staff-control.svg',
  pagos: '/images/staff-control.svg',
  metodosPago: '/images/staff-control.svg',
  servicios: '/images/staff-aeronaves.svg',
  reservaServicios: '/images/staff-asignaciones.svg',
  equipajes: '/images/staff-aeronaves.svg',
  notificaciones: '/images/staff-control.svg',
};
